# Generated by Django 3.2 on 2021-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('datebought', models.DateField()),
                ('username', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Buystock',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=60)),
                ('ticker', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('datebought', models.DateField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dateofbirth', models.DateField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=20, null=True)),
                ('address1', models.CharField(max_length=60, null=True)),
                ('address2', models.CharField(max_length=60, null=True)),
                ('state', models.CharField(max_length=25, null=True)),
                ('postcode', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('country', models.CharField(max_length=25, null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Stbuy',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stockd',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=60)),
                ('ticker', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('datebought', models.DateField()),
                ('price', models.FloatField()),
                ('lastprice', models.FloatField()),
                ('change', models.FloatField()),
                ('type', models.CharField(max_length=60, null=True)),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('balance', models.FloatField(null=True)),
            ],
        ),
    ]
