# Generated by Django 3.2 on 2021-05-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buystock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('ticker', models.CharField(max_length=25)),
                ('quantity', models.IntegerField(max_length=20)),
                ('datebought', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to='photos'),
        ),
    ]
