# Generated by Django 3.2 on 2021-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_auto_20210505_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystock',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
