# Generated by Django 3.2 on 2021-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_alter_buystock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystock',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
