# Generated by Django 3.2 on 2021-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_alter_stockd_lastprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockd',
            name='change',
            field=models.FloatField(null=True),
        ),
    ]
