# Generated by Django 3.2 on 2021-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0007_buystock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystock',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
