# Generated by Django 3.2 on 2021-05-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0011_buystock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystock',
            name='price',
            field=models.FloatField(),
        ),
    ]
