# Generated by Django 3.2 on 2021-05-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0013_stockdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='change',
            field=models.FloatField(default=25),
            preserve_default=False,
        ),
    ]
