# Generated by Django 3.2 on 2021-05-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0014_stockdetails_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='profit',
            field=models.FloatField(default='loss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
