# Generated by Django 3.2 on 2021-05-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0014_stockdetails_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='stockdetails',
            name='type',
        ),
    ]
