# Generated by Django 3.2 on 2021-05-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0016_auto_20210506_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='profit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
