# Generated by Django 3.2 on 2021-05-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0017_auto_20210506_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='stockdetails',
            name='type',
        ),
    ]
