# Generated by Django 3.2 on 2021-05-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0019_auto_20210506_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='profit',
        ),
    ]
