# Generated by Django 3.2 on 2021-05-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0020_remove_stockdetails_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='profit',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
