# Generated by Django 3.2 on 2021-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0023_stockdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=60)),
                ('ticker', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('datebought', models.DateField()),
                ('price', models.FloatField()),
                ('lastprice', models.FloatField()),
                ('change', models.FloatField()),
                ('type', models.CharField(max_length=60, null=True)),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='StockDetails',
        ),
    ]
