# Generated by Django 3.2 on 2021-05-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0026_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
