# Generated by Django 3.2 on 2021-05-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0028_stockd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stbuy',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
    ]
