# Generated by Django 3.2 on 2021-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0029_stbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stbuy',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
