# Generated by Django 3.2 on 2021-05-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0034_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='experience_in_stock_market.png', null=True, upload_to=''),
        ),
    ]
