# Generated by Django 3.2 on 2021-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0036_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='C:/Users/lohit/PycharmProjects/StockExchangeSystem/SES/media/PngItem_4873678.png', null=True, upload_to=''),
        ),
    ]
