# Generated by Django 3.2 on 2021-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0038_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='PngItem_4873678.png', null=True, upload_to=''),
        ),
    ]
