# Generated by Django 3.2 on 2021-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0048_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(null=True),
        ),
    ]
